name: Lint & Test

on:
  push:
    branches:
      - master
      - next
      - beta
  pull_request:
    branches:
      - master
      - next
      - beta

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing dependencies
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
